server:
  port: 8080 #服务端口

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/ #jsp路径前缀
      suffix: .jsp #jsp路径后缀
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #实例化数据库连接类
    url: jdbc:mysql://localhost:3306/duoduogou #数据库连接路径 localhost:3306/wechat
    username: root #数据库连接名 wechat
    password: root #数据库连接密码 wechat3306mysql
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动
    max-idle: 10 #最大的空闲连接
    max-wait: 1000 #等待连接返回的最大等待时间，毫秒单位
    min-idle: 5 #最小的空闲连接
    initial-size: 5 #数据库初始连接
    timeBetweenEvictionRunsMillis: 60000 #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
    minEvictableIdleTimeMillis: 300000 #空闲连接最少空闲多久后可被清除
    validationQuery: select 'x' #获取连接时连接校验的sql查询语句
    testWhileIdle: true #当连接空闲时，是否执行连接测试
    testOnBorrow: false #当从连接池借用连接时，是否测试该连接
    testOnReturn: true #在连接归还到连接池时是否测试该连接
    poolPreparedStatements: true #指定是否池化statements
    maxOpenPreparedStatements: 50 #最大的打开的prepared statements数量

#MyBatis配置
mybatis:
  mapper-locations: classpath:mapping/*/*.xml #Mapper配置文件扫描路径
  type-aliases-package: wang.goods.pojo #pojo类别名包

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#日志配置
logging:
  level:
    wang.goods.mapper: DEBUG #打印sql语句



